export const FETCH_REQUEST='FETCH_REQUEST';
export const FETCH_SUCCESSFULL='FETCH_SUCCESSFULL';
export const FETCH_FAILED='FETCH_FAILED';
export const LOGIN_REQUEST='LOGIN_REQUEST';
export const LOGIN_SUCCESSFULL='LOGIN_SUCCESSFULL';
export const LOGIN_FAILED='LOGIN_FAILED';

